FROM ghcr.io/astral-sh/uv:python3.12-trixie AS python-deps

RUN adduser carbench
USER carbench
RUN mkdir -p /home/carbench/.cache/uv
WORKDIR /home/carbench/app

COPY --chown=carbench:carbench pyproject.toml uv.lock README.md ./
COPY --chown=carbench:carbench third_party third_party

RUN \
    --mount=type=cache,target=/home/carbench/.cache/uv,uid=1000 \
    uv sync --frozen --no-install-project --no-dev --extra track-1-agent

FROM ghcr.io/astral-sh/uv:python3.12-trixie

RUN adduser carbench
USER carbench
WORKDIR /home/carbench/app

COPY --from=python-deps --chown=carbench:carbench /home/carbench/app/.venv .venv
COPY --chown=carbench:carbench src src

ENV PYTHONPATH=/home/carbench/app/src

ENTRYPOINT [".venv/bin/python", "src/my_agent/server.py"]
CMD ["--host", "0.0.0.0"]
EXPOSE 8080
